create database payroll_service;
show databases;
use payroll_service;
Create Table employee_payroll (id int not null auto_increment,name varchar(100),salary double not null, startDate date not null ,primary key(id));
desc employee_payroll;
insert into employee_payroll(name,salary,startDate) values('subham',5000,'2021-07-10');
insert into employee_payroll(name,salary,startDate) values('avishek',8000,'2021-01-10');
insert into employee_payroll(name,salary,startDate) values('saurav',11000,'2021-05-11');
select * from employee_payroll;
select * from employee_payroll where name = 'subham';
select * from employee_payroll where salary = 8000;
select * from employee_payroll where startDate between '2021-05-11' And date(now());
alter table employee_payroll add gender char(1);
update employee_payroll set gender = 'm' where name ='subham';
update employee_payroll set gender = 'm' where name ='avishek';
update employee_payroll set gender = 'm' where name ='saurav';
select gender,min(salary) from employee_payroll;
select gender,max(salary) from employee_payroll;
select gender,avg(salary) from employee_payroll;
select count(gender) from employee_payroll;
select count(salary) from employee_payroll;
select count(salary) from employee_payroll where gender='m';
